version: '3'
services:
  catanie:
    ports:
    - "4200:4200"
    build:
      context: catanie
  catamel:
    ports:
    - "3000:3000"
    build:
      context: catamel
    depends_on:
    - mongodb
  mongodb:
    image: mongo:3.6.5-jessie
  create-index:
    build:
      context: create-index
    depends_on:
    - catamel
